In [4]:
from pathlib import Path

import kagglehub
import pandas as pd

c:\Users\Петр\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
player_path = Path(
    kagglehub.dataset_download("jackogozaly/steam-player-data")
)

games_path = Path(
    kagglehub.dataset_download("fronkongames/steam-games-dataset")
)

reviews_path = Path(
    kagglehub.dataset_download(
        "forgemaster/steam-reviews-dataset",
        path="reviews-1-115.csv"
    )
)

print("Player data:", player_path)
print("Games:", games_path)
print("Reviews:", reviews_path)

Player data: C:\Users\Петр\.cache\kagglehub\datasets\jackogozaly\steam-player-data\versions\1
Games: C:\Users\Петр\.cache\kagglehub\datasets\fronkongames\steam-games-dataset\versions\52
Reviews: C:\Users\Петр\.cache\kagglehub\datasets\forgemaster\steam-reviews-dataset\versions\1\reviews-1-115.csv

In [6]:
print("PLAYER DATA:")
for file in player_path.iterdir():
    print(file.name)

print("\nGAMES:")
for file in games_path.iterdir():
    print(file.name)

print("\nREVIEWS:")
print(reviews_path.name)

PLAYER DATA:
Valve_Player_Data.csv

GAMES:
games.csv
games.json

REVIEWS:
reviews-1-115.csv

In [24]:
player_df = pd.read_csv(
    player_path / "Valve_Player_Data.csv"
)

games_df = pd.read_csv(
    games_path / "games.csv", index_col=False
)

reviews_df = pd.read_csv(
    reviews_path,
    compression="zip"
)

print("Данные загружены")

Данные загружены

In [25]:
datasets = {
    "PLAYER": player_df,
    "GAMES": games_df,
    "REVIEWS": reviews_df
}

for name, df in datasets.items():
    print(f"\n{name}")
    print(f"Строк: {df.shape[0]:,}")
    print(f"Столбцов: {df.shape[1]}")
    print("Колонки:")
    print(df.columns.tolist())

PLAYER
Строк: 5,271
Столбцов: 8
Колонки:
['Month_Year', 'Avg_players', 'Gain', 'Percent_Gain', 'Peak_Players', 'URL', 'Date', 'Game_Name']

GAMES
Строк: 125,855
Столбцов: 39
Колонки:
['AppID', 'Name', 'Release date', 'Estimated owners', 'Peak CCU', 'Required age', 'Price', 'DiscountDLC count', 'About the game', 'Supported languages', 'Full audio languages', 'Reviews', 'Header image', 'Website', 'Support url', 'Support email', 'Windows', 'Mac', 'Linux', 'Metacritic score', 'Metacritic url', 'User score', 'Positive', 'Negative', 'Score rank', 'Achievements', 'Recommendations', 'Notes', 'Average playtime forever', 'Average playtime two weeks', 'Median playtime forever', 'Median playtime two weeks', 'Developers', 'Publishers', 'Categories', 'Genres', 'Tags', 'Screenshots', 'Movies']

REVIEWS
Строк: 1,460,621
Столбцов: 13
Колонки:
['steamid', 'appid', 'voted_up', 'votes_up', 'votes_funny', 'weighted_vote_score', 'playtime_forever', 'playtime_at_review', 'num_games_owned', 'num_reviews', 'review', 'unix_timestamp_created', 'unix_timestamp_updated']

In [26]:
display(player_df.head())
display(games_df.head())
display(reviews_df.head())

,Month_Year,Avg_players,Gain,Percent_Gain,Peak_Players,URL,Date,Game_Name
0,September 2021,512350.92,268.96,+0.05%,942519,https://steamcharts.com/app/730,2021-09-01,Counter Strike: Global Offensive
1,August 2021,512081.96,6014.60,+1.19%,802544,https://steamcharts.com/app/730,2021-08-01,Counter Strike: Global Offensive
2,July 2021,506067.36,-43279.72,-7.88%,763523,https://steamcharts.com/app/730,2021-07-01,Counter Strike: Global Offensive
3,June 2021,549347.08,-110541.81,-16.75%,929940,https://steamcharts.com/app/730,2021-06-01,Counter Strike: Global Offensive
4,May 2021,659888.89,-63457.63,-8.77%,1087197,https://steamcharts.com/app/730,2021-05-01,Counter Strike: Global Offensive

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",...,8,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...",...,0,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",...,0,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...
4,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,...,0,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...

,steamid,appid,voted_up,votes_up,votes_funny,weighted_vote_score,playtime_forever,playtime_at_review,num_games_owned,num_reviews,review,unix_timestamp_created,unix_timestamp_updated
0,76561198107294407,10,True,0,0,0.0,8549,8549,3,1,best gameplay ever created,1619038050,1619038050
1,76561198011733201,10,True,0,0,0.0,25381,25381,74,1,Timeless. Thank you volvo.,1619013754,1619013754
2,76561198168961276,10,True,0,0,0.0,681,616,26,6,this game literally made me love guns and fps ...,1619008681,1619008681
3,76561198957877160,10,True,0,0,0.0,2071,1990,5,1,If this gets a rework in 2021 it's going to be...,1619003706,1619003706
4,76561199050314447,10,True,0,0,0.0,36718,36718,3,1,ok,1618994842,1618994842

## Первичная подготовка данных

Приведение ключевых полей источников к единому формату, преобразование дат и проверка возможности объединения данных.

In [ ]:
player_df["appid"] = (
    player_df["URL"]
    .str.extract(r"/app/(\d+)")
    .astype("Int64")
)


games_df = games_df.reset_index()

if "AppID" in games_df.columns:
    games_df = games_df.rename(columns={"AppID": "appid"})
elif "index" in games_df.columns:
    games_df = games_df.rename(columns={"index": "appid"})

player_df["Date"] = pd.to_datetime(
    player_df["Date"],
    errors="coerce"
)

reviews_df["review_date"] = pd.to_datetime(
    reviews_df["unix_timestamp_created"],
    unit="s",
    errors="coerce"
)

display(player_df[["Game_Name", "appid", "Date"]].head())
display(games_df[["appid", "Name", "Release date"]].head())
display(reviews_df[["appid", "review_date", "voted_up"]].head())

                          Game_Name  appid       Date
0  Counter Strike: Global Offensive    730 2021-09-01
1  Counter Strike: Global Offensive    730 2021-08-01
2  Counter Strike: Global Offensive    730 2021-07-01
3  Counter Strike: Global Offensive    730 2021-06-01
4  Counter Strike: Global Offensive    730 2021-05-01

     appid                                   Name  Release date
0  2539430             Black Dragon Mage Playtest   Aug 1, 2023
1   496350  Supipara - Chapter 1 Spring Has Come!  Jul 29, 2016
2  1034400      Mystery Solitaire The Black Raven   May 6, 2019
3  3292190            버튜버 파라노이아 - Vtuber Paranoia  Oct 31, 2024
4  3631080                          Maze Quest VR  Apr 24, 2025

   appid         review_date  voted_up
0     10 2021-04-21 20:47:30      True
1     10 2021-04-21 14:02:34      True
2     10 2021-04-21 12:38:01      True
3     10 2021-04-21 11:15:06      True
4     10 2021-04-21 08:47:22      True

In [28]:
player_ids = set(player_df["appid"].dropna().astype(int))
games_ids = set(games_df["appid"].dropna().astype(int))
review_ids = set(reviews_df["appid"].dropna().astype(int))

print("Уникальных игр в PLAYER:", len(player_ids))
print("Есть в GAMES:", len(player_ids & games_ids))
print("Есть в REVIEWS:", len(player_ids & review_ids))
print("Есть одновременно во всех источниках:",
      len(player_ids & games_ids & review_ids))

Уникальных игр в PLAYER: 98
Есть в GAMES: 91
Есть в REVIEWS: 5
Есть одновременно во всех источниках: 5

In [29]:
history_stats = (
    player_df.groupby(["appid", "Game_Name"])
    .size()
    .sort_values(ascending=False)
)

print(history_stats.describe())
print()
print(history_stats.head(10))
print()
print(history_stats.tail(10))

count     98.000000
mean      53.785714
std       36.560993
min        1.000000
25%       16.000000
50%       58.500000
75%       82.000000
max      111.000000
dtype: float64

appid   Game_Name
10      Counter-Strike                      111
440     Team Fortress 2                     111
480     Spacewar                            111
550     Left 4 Dead 2                       111
570     Dota 2                              111
730     Counter Strike: Global Offensive    111
4000    Garry's Mod                         111
8930    Sid Meier's Civilization V          111
105600  Terraria                            111
218620  PAYDAY 2                            110
dtype: int64

appid    Game_Name
1366540  Dyson Sphere Program              9
892970   Valheim                           8
1293830  Forza Horizion 4                  7
1623660  MIR4                              2
1254120  Bless Unleashed                   2
1203220  NARAKA: BLADEPOINT                2
740130   Tales of Arise                    1
1184370  Pathfinder: Wrath of Righteous    1
1454400  Cookie Clicker                    1
1644960  NBA 2k22                          1
dtype: int64

## Анализ качества данных

Проверка исходных данных на наличие пропущенных значений, дубликатов и некорректных значений перед дальнейшей обработкой.

In [31]:
def data_quality(df, name):
    print(f"\n{name}")

    print("Размер:", df.shape)
    print("Дубликатов:", df.duplicated().sum())

    missing = df.isna().sum()
    missing = missing[missing > 0].sort_values(ascending=False)

    print("\nПропуски:")
    if len(missing) == 0:
        print("Нет")
    else:
        print(missing)


data_quality(player_df, "PLAYER")
data_quality(games_df, "GAMES")
data_quality(reviews_df, "REVIEWS")

PLAYER
Размер: (5271, 9)
Дубликатов: 0

Пропуски:
Gain            98
Percent_Gain    98
dtype: int64

GAMES
Размер: (125855, 40)
Дубликатов: 0

Пропуски:
Achievements                125815
User score                  121597
Header image                113674
Average playtime forever    102545
Support url                  75335
Support email                70560
Screenshots                  42502
Windows                      22630
Genres                        8966
Categories                    8922
Supported languages           8462
Publishers                    8449
Tags                          8423
Movies                        6027
Website                         81
Name                             1
dtype: int64

REVIEWS
Размер: (1460621, 14)
Дубликатов: 47

Пропуски:
review    1812
dtype: int64

In [32]:
print("PLAYER")
display(
    player_df[
        ["Avg_players", "Gain", "Peak_Players"]
    ].describe()
)

print("\nGAMES")
display(
    games_df[
        ["Price", "Peak CCU", "Positive", "Negative",
         "Recommendations", "Metacritic score"]
    ].describe()
)

print("\nREVIEWS")
display(
    reviews_df[
        ["votes_up", "votes_funny", "weighted_vote_score",
         "playtime_forever", "playtime_at_review"]
    ].describe()
)

PLAYER

        Avg_players           Gain  Peak_Players
count  5.271000e+03    5173.000000  5.271000e+03
mean   3.763149e+04      92.071786  7.032072e+04
std    1.032951e+05   15161.864515  1.941948e+05
min    0.000000e+00 -250248.990000  0.000000e+00
25%    6.720205e+03   -1374.480000  1.302900e+04
50%    1.235840e+04      -0.080000  2.344700e+04
75%    2.414976e+04    1255.140000  4.610150e+04
max    1.584887e+06  426446.120000  3.236027e+06

GAMES

,Price,Peak CCU,Positive,Negative,Recommendations
count,125855.000000,1.258550e+05,125855.000000,1.258550e+05,125855.000000
mean,4.811174,5.318720e+01,0.023916,1.018182e+03,17.922220
std,12.489329,3.681083e+03,1.376811,2.772782e+04,139.696425
min,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000
25%,0.590000,0.000000e+00,0.000000,0.000000e+00,0.000000
50%,2.390000,0.000000e+00,0.000000,4.000000e+00,2.000000
75%,5.545000,0.000000e+00,0.000000,3.500000e+01,19.000000
max,999.980000,1.013936e+06,100.000000,7.642084e+06,9821.000000

REVIEWS

,votes_up,votes_funny,weighted_vote_score,playtime_forever,playtime_at_review
count,1.460621e+06,1.460621e+06,1.460621e+06,1.460621e+06,1.460621e+06
mean,9.671051e-01,2.587652e+05,1.800239e-01,4.702015e+04,2.344979e+04
std,2.617371e+01,3.333646e+07,2.458026e-01,6.881892e+04,4.110358e+04
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,0.000000e+00,0.000000e+00,0.000000e+00,2.265000e+03,9.720000e+02
50%,0.000000e+00,0.000000e+00,0.000000e+00,2.167100e+04,6.960000e+03
75%,1.000000e+00,0.000000e+00,5.000000e-01,6.664200e+04,2.927100e+04
max,1.037900e+04,4.294967e+09,9.778220e-01,4.016239e+06,3.613888e+06

In [33]:
player_clean = player_df.copy()

player_clean = player_clean.sort_values(
    ["appid", "Date"]
).reset_index(drop=True)

player_clean = player_clean.dropna(
    subset=["appid", "Date", "Avg_players", "Peak_Players"]
)

print("Отрицательных Avg_players:",
      (player_clean["Avg_players"] < 0).sum())

print("Отрицательных Peak_Players:",
      (player_clean["Peak_Players"] < 0).sum())

print("Строк после очистки:", len(player_clean))

Отрицательных Avg_players: 0
Отрицательных Peak_Players: 0
Строк после очистки: 5271

In [34]:
games_clean = games_df[
    games_df["appid"].isin(player_ids)
].copy()

print("Строк GAMES до фильтрации:", len(games_df))
print("Строк после фильтрации:", len(games_clean))
print("Уникальных игр:", games_clean["appid"].nunique())

missing_games = player_ids - set(games_clean["appid"])

print("\nИгры PLAYER, которых нет в GAMES:")
print(len(missing_games))

display(
    player_clean[
        player_clean["appid"].isin(missing_games)
    ][["appid", "Game_Name"]]
    .drop_duplicates()
)

Строк GAMES до фильтрации: 125855
Строк после фильтрации: 91
Уникальных игр: 91

Игры PLAYER, которых нет в GAMES:
7

        appid                         Game_Name
222       480                          Spacewar
5136  1225330                          NBA 2k21
5183  1259970  eFootball PES 2021 SEASON UPDATE
5207  1281930                        tModLoader
5224  1293830                  Forza Horizion 4
5243  1329410                 雀魂麻将(MahjongSoul)
5270  1644960                          NBA 2k22

In [35]:
reviews_clean = reviews_df[
    reviews_df["appid"].isin(player_ids)
].copy()

print("Отзывов до фильтрации:", len(reviews_df))
print("Отзывов для игр PLAYER:", len(reviews_clean))
print("Игр с отзывами:", reviews_clean["appid"].nunique())

display(
    reviews_clean.groupby("appid")
    .size()
    .sort_values(ascending=False)
)

Отзывов до фильтрации: 1460621
Отзывов для игр PLAYER: 1114453
Игр с отзывами: 5

appid
730    976212
550    103661
10      22313
440      6166
570      6101
dtype: int64

In [36]:
game_features = [
    "appid",
    "Name",
    "Release date",
    "Estimated owners",
    "Required age",
    "Price",
    "Windows",
    "Mac",
    "Linux",
    "Metacritic score",
    "Positive",
    "Negative",
    "Recommendations",
    "Average playtime forever",
    "Median playtime forever",
    "Developers",
    "Publishers",
    "Categories",
    "Genres",
    "Tags"
]

games_clean = games_clean[game_features].copy()

display(games_clean.head())

,appid,Name,Release date,Estimated owners,Required age,Price,Windows,Mac,Linux,Metacritic score,Positive,Negative,Recommendations,Average playtime forever,Median playtime forever,Developers,Publishers,Categories,Genres,Tags
1111,227300,Euro Truck Simulator 2,"Oct 12, 2012",10000000 - 20000000,0,4.99,support@eurotrucksimulator2.com,True,True,True,0,844480,105,NaN,564,196,SCS Software,SCS Software,"Single-player,Multi-player,Co-op,Online Co-op,...","Indie,Simulation"
1993,629520,Soundpad,"Sep 30, 2017",2000000 - 5000000,0,3.99,support@leppsoft.com,True,False,False,0,84918,0,NaN,418,77,Leppsoft,Leppsoft,Family Sharing,"Audio Production,Utilities"
3692,218620,PAYDAY 2,"Aug 13, 2013",20000000 - 50000000,18,0.99,NaN,True,False,True,0,594327,1328,PAYDAY 2 is a bank robbing game that glorifies...,1735,736,OVERKILL - a Starbreeze Studio.,Starbreeze Entertainment,"Single-player,Multi-player,Co-op,Online Co-op,...","Action,RPG"
4117,1097150,Fall Guys,"Aug 3, 2020",20000000 - 50000000,0,0.00,NaN,True,False,False,0,385154,34,NaN,81,55,Mediatonic,NaN,"Multi-player,MMO,PvP,Online PvP,Co-op,Online C...","Action,Casual,Indie,Massively Multiplayer,Sports"
4193,570,Dota 2,"Jul 9, 2013",100000000 - 200000000,0,0.00,NaN,True,True,True,0,2037143,0,"Dota 2 includes fantasy violence, use of alcoh...",1427,860,Valve,Valve,"Multi-player,Co-op,Steam Trading Cards,Steam W...","Action,Strategy,Free To Play"

In [37]:
games_clean["Release date"] = pd.to_datetime(
    games_clean["Release date"],
    format="mixed",
    errors="coerce"
)

print("Не удалось распознать дат:",
      games_clean["Release date"].isna().sum())

display(
    games_clean[
        ["appid", "Name", "Release date"]
    ].head()
)

Не удалось распознать дат: 0

        appid                    Name Release date
1111   227300  Euro Truck Simulator 2   2012-10-12
1993   629520                Soundpad   2017-09-30
3692   218620                PAYDAY 2   2013-08-13
4117  1097150               Fall Guys   2020-08-03
4193      570                  Dota 2   2013-07-09

In [38]:
missing = games_clean.isna().sum()
missing = missing[missing > 0].sort_values(ascending=False)

print(missing)

Average playtime forever    67
Windows                     54
Categories                   1
dtype: int64

In [39]:
games_clean = games_clean.drop(
    columns=["Average playtime forever"]
)

games_clean["Windows"] = games_clean["Windows"].fillna(False)
games_clean["Categories"] = games_clean["Categories"].fillna("Unknown")

print("Осталось пропусков:", games_clean.isna().sum().sum())
print("Размер:", games_clean.shape)

Осталось пропусков: 0
Размер: (91, 19)

In [40]:
def owners_to_numeric(value):
    if pd.isna(value):
        return None

    parts = str(value).replace(",", "").split("-")

    if len(parts) != 2:
        return None

    lower = float(parts[0].strip())
    upper = float(parts[1].strip())

    return (lower + upper) / 2


games_clean["Estimated owners"] = (
    games_clean["Estimated owners"]
    .apply(owners_to_numeric)
)

In [41]:
display(
    games_clean[
        ["appid", "Name", "Estimated owners", "Price",
         "Genres", "Categories"]
    ].head(10)
)

print("\nТипы:")
print(
    games_clean[
        ["Estimated owners", "Price", "Required age"]
    ].dtypes
)

,appid,Name,Estimated owners,Price,Genres,Categories
1111,227300,Euro Truck Simulator 2,15000000.0,4.99,"Single-player,Multi-player,Co-op,Online Co-op,...",SCS Software
1993,629520,Soundpad,3500000.0,3.99,Family Sharing,Leppsoft
3692,218620,PAYDAY 2,35000000.0,0.99,"Single-player,Multi-player,Co-op,Online Co-op,...",Starbreeze Entertainment
4117,1097150,Fall Guys,35000000.0,0.00,"Multi-player,MMO,PvP,Online PvP,Co-op,Online C...",Unknown
4193,570,Dota 2,150000000.0,0.00,"Multi-player,Co-op,Steam Trading Cards,Steam W...",Valve
5107,526870,Satisfactory,15000000.0,27.99,"Single-player,Multi-player,Co-op,Online Co-op,...",Coffee Stain Publishing
5377,252490,Rust,35000000.0,19.99,"Multi-player,MMO,PvP,Online PvP,Co-op,Online C...",Facepunch Studios
6006,552990,World of Warships,35000000.0,0.00,"Multi-player,MMO,PvP,Online PvP,Co-op,Online C...",Wargaming Group Limited
8525,294100,RimWorld,7500000.0,27.99,"Single-player,Steam Workshop,Partial Controlle...",Ludeon Studios
8773,513710,SCUM,7500000.0,17.99,"Single-player,Multi-player,MMO,PvP,Online PvP,...",Gamepires

Типы:
Estimated owners    float64
Price               float64
Required age          int64
dtype: object

## Подготовка данных об отзывах

Отзывы агрегируются по игре и месяцу для формирования признаков, характеризующих пользовательскую активность и отношение игроков.

In [42]:
reviews_clean["month"] = (
    reviews_clean["review_date"]
    .dt.to_period("M")
    .dt.to_timestamp()
)

reviews_clean["voted_up"] = (
    reviews_clean["voted_up"].astype(int)
)

print("Период отзывов:")
print(reviews_clean["review_date"].min())
print(reviews_clean["review_date"].max())

print("\nКоличество отзывов:", len(reviews_clean))
print("Количество игр:", reviews_clean["appid"].nunique())

Период отзывов:
2010-10-15 22:27:49
2021-04-22 00:34:08

Количество отзывов: 1114453
Количество игр: 5

In [43]:
reviews_monthly = (
    reviews_clean
    .groupby(["appid", "month"])
    .agg(
        review_count=("review", "size"),
        positive_share=("voted_up", "mean"),
        avg_playtime=("playtime_forever", "mean"),
        avg_votes_up=("votes_up", "mean")
    )
    .reset_index()
)

display(reviews_monthly.head(10))

print("Размер агрегированной таблицы:", reviews_monthly.shape)

   appid      month  review_count  positive_share   avg_playtime  avg_votes_up
0     10 2010-11-01            13        1.000000   82125.769231      0.923077
1     10 2010-12-01            23        0.956522   55806.739130      0.304348
2     10 2011-01-01            24        1.000000  262547.708333      0.791667
3     10 2011-02-01            12        1.000000  117957.666667      0.333333
4     10 2011-03-01            16        0.937500   90840.687500      0.500000
5     10 2011-04-01            10        1.000000   73337.400000      0.100000
6     10 2011-05-01             5        1.000000   96524.200000      0.000000
7     10 2011-06-01            16        1.000000   37311.000000      0.187500
8     10 2011-07-01            51        1.000000   75051.333333      0.117647
9     10 2011-08-01            23        0.956522   70427.869565      0.173913

Размер агрегированной таблицы: (473, 6)

In [44]:
player_clean["month"] = (
    player_clean["Date"]
    .dt.to_period("M")
    .dt.to_timestamp()
)

In [46]:
display(
    player_clean[
        ["appid", "Game_Name", "month", "Avg_players", "Peak_Players"]
    ].head()
)

   appid       Game_Name      month  Avg_players  Peak_Players
0     10  Counter-Strike 2012-07-01     34139.20         53967
1     10  Counter-Strike 2012-08-01     33095.80         53685
2     10  Counter-Strike 2012-09-01     29432.56         55321
3     10  Counter-Strike 2012-10-01     28836.29         56053
4     10  Counter-Strike 2012-11-01     29669.97         56957

In [47]:
dataset = player_clean.merge(
    reviews_monthly,
    on=["appid", "month"],
    how="left"
)

print("PLAYER до объединения:", len(player_clean))
print("После объединения:", len(dataset))

print(
    "Строк с данными об отзывах:",
    dataset["review_count"].notna().sum()
)

print(
    "Игр с данными об отзывах:",
    dataset.loc[
        dataset["review_count"].notna(),
        "appid"
    ].nunique()
)

PLAYER до объединения: 5271
После объединения: 5271
Строк с данными об отзывах: 427
Игр с данными об отзывах: 5

In [48]:
dataset = dataset.merge(
    games_clean,
    on="appid",
    how="left"
)

print("Строк после добавления GAMES:", len(dataset))
print("Уникальных игр:", dataset["appid"].nunique())

Строк после добавления GAMES: 5271
Уникальных игр: 98

In [49]:
dataset = dataset.sort_values(
    ["appid", "month"]
).reset_index(drop=True)

In [50]:
dataset["target_next_month"] = (
    dataset
    .groupby("appid")["Avg_players"]
    .shift(-1)
)

In [51]:
display(
    dataset[
        ["appid", "Game_Name", "month",
         "Avg_players", "target_next_month"]
    ].head(10)
)

print(
    "Строк без target:",
    dataset["target_next_month"].isna().sum()
)

   appid       Game_Name      month  Avg_players  target_next_month
0     10  Counter-Strike 2012-07-01     34139.20           33095.80
1     10  Counter-Strike 2012-08-01     33095.80           29432.56
2     10  Counter-Strike 2012-09-01     29432.56           28836.29
3     10  Counter-Strike 2012-10-01     28836.29           29669.97
4     10  Counter-Strike 2012-11-01     29669.97           31996.07
5     10  Counter-Strike 2012-12-01     31996.07           34814.47
6     10  Counter-Strike 2013-01-01     34814.47           28378.42
7     10  Counter-Strike 2013-02-01     28378.42           24139.15
8     10  Counter-Strike 2013-03-01     24139.15           21204.46
9     10  Counter-Strike 2013-04-01     21204.46           19900.81

Строк без target: 98

In [52]:
grouped = dataset.groupby("appid")

dataset["avg_players_lag_1"] = (
    grouped["Avg_players"].shift(1)
)

dataset["avg_players_lag_3"] = (
    grouped["Avg_players"].shift(3)
)

dataset["avg_players_lag_6"] = (
    grouped["Avg_players"].shift(6)
)

In [53]:
dataset["avg_players_roll_3"] = (
    grouped["Avg_players"]
    .transform(
        lambda x: x.shift(1).rolling(3).mean()
    )
)

dataset["avg_players_roll_6"] = (
    grouped["Avg_players"]
    .transform(
        lambda x: x.shift(1).rolling(6).mean()
    )
)

In [54]:
dataset["year"] = dataset["month"].dt.year
dataset["month_num"] = dataset["month"].dt.month
dataset["quarter"] = dataset["month"].dt.quarter

In [55]:
dataset["game_age_months"] = (
    (dataset["month"].dt.year - dataset["Release date"].dt.year) * 12
    + dataset["month"].dt.month
    - dataset["Release date"].dt.month
)

In [56]:
columns_to_check = [
    "appid",
    "Game_Name",
    "month",
    "Avg_players",
    "avg_players_lag_1",
    "avg_players_lag_3",
    "avg_players_lag_6",
    "avg_players_roll_3",
    "avg_players_roll_6",
    "target_next_month"
]

display(dataset[columns_to_check].head(15))

,appid,Game_Name,month,Avg_players,avg_players_lag_1,avg_players_lag_3,avg_players_lag_6,avg_players_roll_3,avg_players_roll_6,target_next_month
0,10,Counter-Strike,2012-07-01,34139.20,NaN,NaN,NaN,NaN,NaN,33095.80
1,10,Counter-Strike,2012-08-01,33095.80,34139.20,NaN,NaN,NaN,NaN,29432.56
2,10,Counter-Strike,2012-09-01,29432.56,33095.80,NaN,NaN,NaN,NaN,28836.29
3,10,Counter-Strike,2012-10-01,28836.29,29432.56,34139.20,NaN,32222.520000,NaN,29669.97
4,10,Counter-Strike,2012-11-01,29669.97,28836.29,33095.80,NaN,30454.883333,NaN,31996.07
5,10,Counter-Strike,2012-12-01,31996.07,29669.97,29432.56,NaN,29312.940000,NaN,34814.47
6,10,Counter-Strike,2013-01-01,34814.47,31996.07,28836.29,34139.20,30167.443333,31194.981667,28378.42
7,10,Counter-Strike,2013-02-01,28378.42,34814.47,29669.97,33095.80,32160.170000,31307.526667,24139.15
8,10,Counter-Strike,2013-03-01,24139.15,28378.42,31996.07,29432.56,31729.653333,30521.296667,21204.46
9,10,Counter-Strike,2013-04-01,21204.46,24139.15,34814.47,28836.29,29110.680000,29639.061667,19900.81
10,10,Counter-Strike,2013-05-01,19900.81,21204.46,28378.42,29669.97,24574.010000,28367.090000,20144.89
11,10,Counter-Strike,2013-06-01,20144.89,19900.81,24139.15,31996.07,21748.140000,26738.896667,20481.43
12,10,Counter-Strike,2013-07-01,20481.43,20144.89,21204.46,34814.47,20416.720000,24763.700000,21297.53
13,10,Counter-Strike,2013-08-01,21297.53,20481.43,19900.81,28378.42,20175.710000,22374.860000,19187.79
14,10,Counter-Strike,2013-09-01,19187.79,21297.53,20144.89,24139.15,20641.283333,21194.711667,19080.85

In [57]:
print(
    dataset[
        [
            "avg_players_lag_1",
            "avg_players_lag_3",
            "avg_players_lag_6",
            "avg_players_roll_3",
            "avg_players_roll_6",
            "target_next_month"
        ]
    ].isna().sum()
)

avg_players_lag_1      98
avg_players_lag_3     283
avg_players_lag_6     556
avg_players_roll_3    283
avg_players_roll_6    556
target_next_month      98
dtype: int64

In [58]:
month_diff = (
    player_clean
    .sort_values(["appid", "month"])
    .groupby("appid")["month"]
    .diff()
)

print(month_diff.value_counts().sort_index())

month
28 days       321
29 days       104
30 days      1689
31 days      3052
62 days         1
120 days        1
184 days        1
212 days        1
213 days        1
426 days        1
1278 days       1
Name: count, dtype: int64

In [59]:
full_rows = []

for appid, group in player_clean.groupby("appid"):
    group = group.sort_values("month").copy()

    full_months = pd.date_range(
        start=group["month"].min(),
        end=group["month"].max(),
        freq="MS"
    )

    group = (
        group
        .set_index("month")
        .reindex(full_months)
        .rename_axis("month")
        .reset_index()
    )

    group["appid"] = appid

    full_rows.append(group)

player_regular = pd.concat(
    full_rows,
    ignore_index=True
)

print("Строк исходно:", len(player_clean))
print("Строк после восстановления календаря:", len(player_regular))
print("Добавлено пропущенных месяцев:",
      len(player_regular) - len(player_clean))

print(
    "Строк без Avg_players:",
    player_regular["Avg_players"].isna().sum()
)

Строк исходно: 5271
Строк после восстановления календаря: 5346
Добавлено пропущенных месяцев: 75
Строк без Avg_players: 75

In [60]:
missing_months = (
    player_regular[
        player_regular["Avg_players"].isna()
    ]
    .groupby("appid")
    .size()
    .sort_values(ascending=False)
)

print(missing_months)

appid
261550    41
779340    13
513710     8
255710     6
281990     6
646570     1
dtype: int64

In [61]:
dataset = player_regular.merge(
    reviews_monthly,
    on=["appid", "month"],
    how="left"
)

dataset = dataset.merge(
    games_clean,
    on="appid",
    how="left"
)

dataset = dataset.sort_values(
    ["appid", "month"]
).reset_index(drop=True)

print("Размер:", dataset.shape)
print("Уникальных игр:", dataset["appid"].nunique())
print("Пропущенных Avg_players:", dataset["Avg_players"].isna().sum())

Размер: (5346, 32)
Уникальных игр: 98
Пропущенных Avg_players: 75

In [62]:
grouped = dataset.groupby("appid")

dataset["target_next_month"] = (
    grouped["Avg_players"].shift(-1)
)

dataset["avg_players_lag_1"] = (
    grouped["Avg_players"].shift(1)
)

dataset["avg_players_lag_3"] = (
    grouped["Avg_players"].shift(3)
)

dataset["avg_players_lag_6"] = (
    grouped["Avg_players"].shift(6)
)

dataset["avg_players_roll_3"] = (
    grouped["Avg_players"]
    .transform(lambda x: x.shift(1).rolling(3).mean())
)

dataset["avg_players_roll_6"] = (
    grouped["Avg_players"]
    .transform(lambda x: x.shift(1).rolling(6).mean())
)

dataset["year"] = dataset["month"].dt.year
dataset["month_num"] = dataset["month"].dt.month
dataset["quarter"] = dataset["month"].dt.quarter

dataset["game_age_months"] = (
    (dataset["month"].dt.year - dataset["Release date"].dt.year) * 12
    + dataset["month"].dt.month
    - dataset["Release date"].dt.month
)

In [64]:
print("Размер dataset:", dataset.shape)
print("Уникальных игр:", dataset["appid"].nunique())

check_cols = [
    "Avg_players",
    "target_next_month",
    "avg_players_lag_1",
    "avg_players_lag_3",
    "avg_players_lag_6",
    "avg_players_roll_3",
    "avg_players_roll_6",
    "game_age_months"
]

print("\nПропуски:")
print(dataset[check_cols].isna().sum())

Размер dataset: (5346, 42)
Уникальных игр: 98

Пропуски:
Avg_players            75
target_next_month     173
avg_players_lag_1     173
avg_players_lag_3     358
avg_players_lag_6     631
avg_players_roll_3    368
avg_players_roll_6    644
game_age_months       177
dtype: int64

In [65]:
display(
    dataset[
        [
            "appid",
            "Game_Name",
            "month",
            "Avg_players",
            "avg_players_lag_1",
            "avg_players_lag_3",
            "avg_players_lag_6",
            "target_next_month"
        ]
    ].head(15)
)

,appid,Game_Name,month,Avg_players,avg_players_lag_1,avg_players_lag_3,avg_players_lag_6,target_next_month
0,10,Counter-Strike,2012-07-01,34139.20,NaN,NaN,NaN,33095.80
1,10,Counter-Strike,2012-08-01,33095.80,34139.20,NaN,NaN,29432.56
2,10,Counter-Strike,2012-09-01,29432.56,33095.80,NaN,NaN,28836.29
3,10,Counter-Strike,2012-10-01,28836.29,29432.56,34139.20,NaN,29669.97
4,10,Counter-Strike,2012-11-01,29669.97,28836.29,33095.80,NaN,31996.07
5,10,Counter-Strike,2012-12-01,31996.07,29669.97,29432.56,NaN,34814.47
6,10,Counter-Strike,2013-01-01,34814.47,31996.07,28836.29,34139.20,28378.42
7,10,Counter-Strike,2013-02-01,28378.42,34814.47,29669.97,33095.80,24139.15
8,10,Counter-Strike,2013-03-01,24139.15,28378.42,31996.07,29432.56,21204.46
9,10,Counter-Strike,2013-04-01,21204.46,24139.15,34814.47,28836.29,19900.81
10,10,Counter-Strike,2013-05-01,19900.81,21204.46,28378.42,29669.97,20144.89
11,10,Counter-Strike,2013-06-01,20144.89,19900.81,24139.15,31996.07,20481.43
12,10,Counter-Strike,2013-07-01,20481.43,20144.89,21204.46,34814.47,21297.53
13,10,Counter-Strike,2013-08-01,21297.53,20481.43,19900.81,28378.42,19187.79
14,10,Counter-Strike,2013-09-01,19187.79,21297.53,20144.89,24139.15,19080.85

In [66]:
model_dataset = dataset.dropna(
    subset=[
        "Avg_players",
        "target_next_month",
        "avg_players_lag_1",
        "avg_players_lag_3",
        "avg_players_lag_6",
        "avg_players_roll_3",
        "avg_players_roll_6"
    ]
).copy()

print("Строк до:", len(dataset))
print("Строк после:", len(model_dataset))
print("Уникальных игр:", model_dataset["appid"].nunique())

Строк до: 5346
Строк после: 4609
Уникальных игр: 90

In [67]:
history_after = (
    model_dataset
    .groupby(["appid", "Game_Name"])
    .size()
)

print(history_after.describe())

print("\nПериод:")
print(model_dataset["month"].min())
print(model_dataset["month"].max())

count     90.000000
mean      51.211111
std       34.628524
min        1.000000
25%       15.250000
50%       54.000000
75%       79.000000
max      104.000000
dtype: float64

Период:
2013-01-01 00:00:00
2021-08-01 00:00:00

In [68]:
print(
    "Строк без характеристик GAMES:",
    model_dataset["Name"].isna().sum()
)

print(
    "Игр без характеристик GAMES:",
    model_dataset.loc[
        model_dataset["Name"].isna(),
        "appid"
    ].nunique()
)

print(
    "Строк с REVIEWS:",
    model_dataset["review_count"].notna().sum()
)

print(
    "Игр с REVIEWS:",
    model_dataset.loc[
        model_dataset["review_count"].notna(),
        "appid"
    ].nunique()
)

Строк без характеристик GAMES: 134
Игр без характеристик GAMES: 5
Строк с REVIEWS: 406
Игр с REVIEWS: 5

In [69]:
feature_columns = [
    "Avg_players",
    "Peak_Players",

    "avg_players_lag_1",
    "avg_players_lag_3",
    "avg_players_lag_6",
    "avg_players_roll_3",
    "avg_players_roll_6",

    "year",
    "month_num",
    "quarter",
]

In [70]:
monthly_counts = (
    model_dataset
    .groupby("month")
    .size()
)

print(monthly_counts)

print("\nНачало:", model_dataset["month"].min())
print("Конец:", model_dataset["month"].max())
print("Количество месяцев:", model_dataset["month"].nunique())

month
2013-01-01     9
2013-02-01    10
2013-03-01    11
2013-04-01    11
2013-05-01    11
              ..
2021-04-01    85
2021-05-01    87
2021-06-01    88
2021-07-01    89
2021-08-01    90
Length: 104, dtype: int64

Начало: 2013-01-01 00:00:00
Конец: 2021-08-01 00:00:00
Количество месяцев: 104

In [71]:
games_per_month = (
    model_dataset
    .groupby("month")["appid"]
    .nunique()
)

display(games_per_month.tail(24))

month
2019-09-01    62
2019-10-01    62
2019-11-01    63
2019-12-01    63
2020-01-01    64
2020-02-01    64
2020-03-01    64
2020-04-01    65
2020-05-01    67
2020-06-01    68
2020-07-01    68
2020-08-01    68
2020-09-01    68
2020-10-01    69
2020-11-01    70
2020-12-01    76
2021-01-01    77
2021-02-01    78
2021-03-01    82
2021-04-01    85
2021-05-01    87
2021-06-01    88
2021-07-01    89
2021-08-01    90
Name: appid, dtype: int64